### ISSUE TITLE
Adding an output command

### ISSUE THREAD

**Issue by xarantolus** [kammt/MemeAssembly#10]
Hi, nice project :)

I would love to write a program that can output text, e.g. certain [links](https://www.youtube.com/watch?v=dQw4w9WgXcQ), to stdout.

After a bit of research i got to the following asm snippet that works on Linux (Ubuntu 19.10) using the exact compile commands used in the program. It doesn't seem to work on Windows Subsystem for Linux though, there I get an `Exec format error`.

Anyways, here's the content of `tmp.asm`:

```nasm
section .text
global main
main:  
    mov al, '!'
    call writechar
      
    ret
    
; Writes the ascii character in al to stdout
writechar:
    push ebx
    push ecx
    push edx
    push eax
    mov edx, 1
    mov ecx, esp
    mov ebx, 1
    mov eax, 4
    int 128
    pop eax
    pop edx
    pop ecx
    pop ebx
    
    ret
```

Compile & run:

    nasm -f elf32 -o tmp.o tmp.asm
    gcc tmp.o -g -o tmp -m32 -fno-pie -no-pie
    ./tmp

This outputs `!` without any newlines etc, as expected. The same snippet also works in SASM.

I adapted the method from [this site](https://montcs.bloomu.edu/~bobmon/Code/Asm.and.C/hello-asms.html) to get a version that works without any external dependencies, just some instructions.

---

Then I tried to add this to the `translator.c` file, but I can't seem to get it right. I changed very little (just entries in the `commandPatterns` and `translationPatterns` arrays), the file is [here](https://github.com/kammt/MemeAssembly/files/6361023/github-doesnt-let-me-upload-it-directly-so-i-had-to-zip-the-file.zip).

The string to insert in `translationPatterns` should probably be `"push ebx\npush ecx\npush edx\npush eax\nmov edx, 1\nmov ecx, esp\nmov ebx, 1\nmov eax, 4\nint 128\npop eax\npop edx\npop ecx\npop ebx",`.

When I tried my change with a file that just contains `much wow` (the command pattern for this, subject to change :D), it generates the following output in `tmp.asm`:

```nasm
section .text
global main
main:
	line_1: 
	push ebx
push ecx
push edx
push eax
mov edx, 1
mov ecx, esp
add 

	ret
```

This doesn't compile and it's where I got stuck. It would be nice if you have any pointers on how to add the command. Thank you :)

**Comment by kammt** [comment]
Hey there!
Thanks for contributing to this repo, you are awesome! :D

So the reason that only the first part of your code is printed is due to the fact that the _commandPattern_ and _translationPattern_ array items are limited to 60 characters, meaning that roughly half of your code is cut off. To fix that, you have two options:

1. Increase the array size of the translationPattern array. However, this means that you have to change the array sizes in some other places as well (Most importantly in line 122, which is the generateASM() function)
2. Like you did in the first example, simply call the function _writechar_ and insert the code for that function at a later point. This could be done  after inserting the ret-statement in the startTranslation() function. (line 320) For the sake of simplicity, I'd probably always insert the function even if it's not used.

Your code currently only supports printing one single character, but that's not a bad thing. Since this programming language is all about ~~making a developer's life miserable~~ minimalism™, this perfectly fits into my "design philosophy" 😛 

My idea for the actual command would be "what can I say except c", derived from [Moana](https://knowyourmeme.com/memes/youre-welcome) (c stands for a character here)
This would however get tricky when we are trying to implement the newline-character or a space, since newline is two characters (in c-notation, so \n) and spaces are ignored by the compiler. One solution could be to add two separate commands for these cases, although I currently don't have an idea for their command-names right now.

If you need any support (for writing certain implementations or simply wanting to know what my code is doing), I'd be happy to help you out! For the first one, you could e.g. fork this repo and invite me as a collaborator. 
Anyway, for a possible implementation, this is the task list:

- [ ] Extend the compileWithPattern-function to support the c-keyword, which stands for a single character. (i.e. check if the string length of the token is 1 and if so add it to the parameter array with surrounding '-symbols)
- [ ] Append the ASM-code for writechar to the end of every compiled file, best done in the startTranslation() function (line 320)
- [ ] change the translationPattern for the new command to be "mov al, 0\n\tcall writechar" (the compiler would then replace 0 with the character)
- [ ] change the commandPattern. I'm open to suggestions here (as for any other step) so let's see what we can come up with!

P.S.: Kudos for that rick-roll
